import type { Source, SourceDefinition } from './types'
import { EMISSION_FACTORS } from './constants'

export const SOURCE_DEFINITIONS: Record<Source, SourceDefinition> = {
  solar: {
    id: 'solar',
    label: 'Solare fotovoltaico',
    labelShort: 'Solare',
    color: '#f59e0b',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.solar,
    dispatchable: false,
    sliderMin: 0,
    sliderMax: 120,
    sliderStep: 1,
  },
  wind_onshore: {
    id: 'wind_onshore',
    label: 'Eolico onshore',
    labelShort: 'Eolico',
    color: '#38bdf8',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.wind_onshore,
    dispatchable: false,
    sliderMin: 0,
    sliderMax: 60,
    sliderStep: 1,
  },
  wind_offshore: {
    id: 'wind_offshore',
    label: 'Eolico offshore',
    labelShort: 'Eolico off.',
    color: '#0ea5e9',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.wind_offshore,
    dispatchable: false,
    sliderMin: 0,
    sliderMax: 30,
    sliderStep: 0.5,
  },
  hydro_run: {
    id: 'hydro_run',
    label: 'Idroelettrico (fluente)',
    labelShort: 'Idro fluente',
    color: '#06b6d4',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.hydro_run,
    dispatchable: false,
    sliderMin: 0,
    sliderMax: 20,
    sliderStep: 0.5,
  },
  hydro_reservoir: {
    id: 'hydro_reservoir',
    label: 'Idroelettrico (serbatoi)',
    labelShort: 'Idro serb.',
    color: '#0891b2',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.hydro_reservoir,
    dispatchable: true,  // can be modulated
    sliderMin: 0,
    sliderMax: 25,
    sliderStep: 0.5,
  },
  biomass: {
    id: 'biomass',
    label: 'Biomasse e biogas',
    labelShort: 'Biomasse',
    color: '#22c55e',
    category: 'dispatchable',
    emissionFactor: EMISSION_FACTORS.biomass,
    dispatchable: true,
    sliderMin: 0,
    sliderMax: 10,
    sliderStep: 0.5,
  },
  geothermal: {
    id: 'geothermal',
    label: 'Geotermico',
    labelShort: 'Geo',
    color: '#a855f7',
    category: 'renewable',
    emissionFactor: EMISSION_FACTORS.geothermal,
    dispatchable: false,
    sliderMin: 0,
    sliderMax: 5,
    sliderStep: 0.1,
  },
  nuclear: {
    id: 'nuclear',
    label: 'Nucleare',
    labelShort: 'Nucleare',
    color: '#6366f1',
    category: 'dispatchable',
    emissionFactor: EMISSION_FACTORS.nuclear,
    dispatchable: false,  // baseload, must-run
    sliderMin: 0,
    sliderMax: 20,
    sliderStep: 0.5,
  },
  gas_ccgt: {
    id: 'gas_ccgt',
    label: 'Gas naturale',
    labelShort: 'Gas',
    color: '#f97316',
    category: 'dispatchable',
    emissionFactor: EMISSION_FACTORS.gas_ccgt,
    dispatchable: true,
    sliderMin: 0,
    sliderMax: 50,
    sliderStep: 1,
  },
  gas_ocgt: {
    id: 'gas_ocgt',
    label: 'Gas naturale (OCGT/peaker)',
    labelShort: 'Gas OCGT',
    color: '#fb923c',
    category: 'dispatchable',
    emissionFactor: EMISSION_FACTORS.gas_ocgt,
    dispatchable: true,
    sliderMin: 0,
    sliderMax: 20,
    sliderStep: 1,
  },
  coal: {
    id: 'coal',
    label: 'Carbone',
    labelShort: 'Carbone',
    color: '#78716c',
    category: 'dispatchable',
    emissionFactor: EMISSION_FACTORS.coal,
    dispatchable: true,
    sliderMin: 0,
    sliderMax: 15,
    sliderStep: 0.5,
  },
  imports: {
    id: 'imports',
    label: 'Importazioni nette',
    labelShort: 'Import',
    color: '#94a3b8',
    category: 'import',
    emissionFactor: EMISSION_FACTORS.imports,
    dispatchable: true,
    sliderMin: 0,
    sliderMax: 15,
    sliderStep: 0.5,
  },
}

/** Render order for stacked charts (bottom → top) */
export const SOURCE_ORDER: Source[] = [
  'coal',
  'gas_ocgt',
  'gas_ccgt',
  'imports',
  'nuclear',
  'biomass',
  'geothermal',
  'hydro_reservoir',
  'hydro_run',
  'wind_offshore',
  'wind_onshore',
  'solar',
]

export const RENEWABLE_SOURCES: Source[] = [
  'solar',
  'wind_onshore',
  'wind_offshore',
  'hydro_run',
  'hydro_reservoir',
  'geothermal',
  'biomass',
  'nuclear',
]

export const DISPATCHABLE_SOURCES: Source[] = ['gas_ccgt', 'gas_ocgt', 'coal', 'imports']

/** Merit order for economic dispatch (cheapest first) */
export const MERIT_ORDER: Source[] = ['hydro_reservoir', 'biomass', 'gas_ccgt', 'gas_ocgt', 'coal', 'imports']
